### ISSUE TITLE
Formal UNV specification

### ISSUE THREAD

**Issue by Pandademic** [UnvLabs/site#10]
Is there a formal UNV specification?

**Comment by ksenginew** [comment]
NO. but planned at https://github.com/UnvLabs/Unv

**Comment by Pandademic** [comment]
Thank you!

**Comment by Pandademic** [comment]
Will it be linked to the site?

**Comment by ksenginew** [comment]
> Will it be linked to the site?

No. like [Sass lang spec](https://github.com/sass/sass)

**Comment by Pandademic** [comment]
OK , thanks!
